language: php
php:
  - '7.4'
install:
  - composer install --prefer-dist -n --no-suggest
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - vendor/bin/phpcs --standard=PSR12 src
  - vendor/bin/phpunit --coverage-clover clover.xml
after_script:
  - ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT
cache:
  directories:
    - $HOME/.composer/cache
